### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Dingxiangtao** [One-paper-luck/MG-Transformer#2]
FileNotFoundError: [Errno 2] No such file or directory: '/media/dmd/ours/mlw/pre_model/resnet152.pth'
前辈，这个media文件夹应该去哪里获取呢？

**Comment by One-paper-luck** [comment]
用的torch提供的预训练模型，下载地址网上搜一下就好了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月09日 10:33 |
| 收件人 | One-paper-luck/MG-Transformer ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [One-paper-luck/MG-Transformer] 缺少文件 (Issue #2) |

FileNotFoundError: [Errno 2] No such file or directory: '/media/dmd/ours/mlw/pre_model/resnet152.pth'
前辈，这个media文件夹应该去哪里获取呢？

**Comment by Dingxiangtao** [comment]
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    train_loss = train_xe(model, dataloader_train, optim, text_field)
  File "train.py", line 98, in train_xe
    out = model(detections, detections_gl, detections_mask, captions, isencoder=True)
  File "/home/tcs/anaconda3/envs/m2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tcs/aaa/dxt/MG-Transformer-main/models/transformer/transformer.py", line 29, in forward
    enc_output, mask_enc = self.encoder(images, images_gl,detections_mask,isencoder=isencoder)
  File "/home/tcs/anaconda3/envs/m2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tcs/aaa/dxt/MG-Transformer-main/models/transformer/encoders.py", line 91, in forward
    input_gl = F.relu(self.fc_clip(input_gl))
  File "/home/tcs/anaconda3/envs/m2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tcs/anaconda3/envs/m2/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/tcs/anaconda3/envs/m2/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2450x512 and 768x512)
前辈，很抱歉这么晚了打扰你，我处理完特征后运行train.py报这个错误，是什么原因呢？按理说应该不会出现维度错误吧。难道预训练权重用的不对

**Comment by Dingxiangtao** [comment]
前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢

**Comment by Lucyhahahahha** [comment]
> 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢

同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？

**Comment by One-paper-luck** [comment]
> > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> 
> 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？

抱歉，忘记回了。
使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):

line 237     if self.proj is not None:
line 238           x = x @ self.proj

所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.

**Comment by Lucyhahahahha** [comment]
> > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > 
> > 
> > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> 
> 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> 
> line 237 if self.proj is not None: line 238 x = x @ self.proj
> 
> 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.

好的好的，谢谢您的耐心解答

**Comment by Lucyhahahahha** [comment]
> > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > 
> > 
> > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> 
> 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> 
> line 237 if self.proj is not None: line 238 x = x @ self.proj
> 
> 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.

作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑

**Comment by One-paper-luck** [comment]
> > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > 
> > > 
> > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > 
> > 
> > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> 
> 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑

RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27

代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。
或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。

**Comment by Lucyhahahahha** [comment]
> > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > 
> > > > 
> > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > 
> > > 
> > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > 
> > 
> > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> 
> RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> 
> 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。

好的好的，我去尝试一下，十分感谢

**Comment by Dingxiangtao** [comment]
> > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > 
> > > > 
> > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > 
> > > 
> > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > 
> > 
> > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> 
> RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> 
> 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。



> > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > 
> > > > 
> > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > 
> > > 
> > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > 
> > 
> > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> 
> RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> 
> 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。

前辈，我有一个问题，RSIC是随机划分数据集的，那我只在对比方法时取平均，其他消融实验只固定一个随机数种子来进行实验，这种是允许的吗？毕竟只要能表现出自己模块的作用不就足够了吗？

**Comment by One-paper-luck** [comment]
> > > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > > 
> > > > > 
> > > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > > 
> > > > 
> > > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > > 
> > > 
> > > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> > 
> > 
> > RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> > 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。
> 
> > > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > > 
> > > > > 
> > > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > > 
> > > > 
> > > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > > 
> > > 
> > > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> > 
> > 
> > RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> > 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。
> 
> 前辈，我有一个问题，RSIC是随机划分数据集的，那我只在对比方法时取平均，其他消融实验只固定一个随机数种子来进行实验，这种是允许的吗？毕竟只要能表现出自己模块的作用不就足够了吗？

是可以的，但主要还是看reviewer的态度

**Comment by Dingxiangtao** [comment]
> > > > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > > > 
> > > > > > 
> > > > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > > > 
> > > > > 
> > > > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > > > 
> > > > 
> > > > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> > > 
> > > 
> > > RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> > > 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。
> > 
> > 
> > > > > > > 前辈，问题解决了，MemoryAugmentedEncoder中clip维度应该改为512，那这个768对应的是那个数据集的维度呢
> > > > > > 
> > > > > > 
> > > > > > 同问，请问Ding前辈解决这个疑惑了么？论文中提到使用Clip Vit-B/32提取的特征维度是768，但是代码运行pre_Clip_feature.py输出特征是512维度呀，请问这是怎么回事？
> > > > > 
> > > > > 
> > > > > 抱歉，忘记回了。 使用pre_Clip_feature.py的时候， 先注释了了CLIP官方文件.clip/model.py中 VisionTransformer line 237-238(最后一个全连接层):
> > > > > line 237 if self.proj is not None: line 238 x = x @ self.proj
> > > > > 所以提取的特征维度是768. 在我们的编码器中又投影到d_model=512.
> > > > 
> > > > 
> > > > 作者您好，按照您的办法，我注释了.clip/model.py中237行与238行，没有对代码其他部分更改，并在Sydney-Captions数据集上进行实验。但是在各个指标的得分都与论文中的结果相差4个点以上，感到十分困惑
> > > 
> > > 
> > > RSIC许多方法是随机划分数据集，为了公平比较，这个工作采用五个不同的划分，去掉最优和最差，求的均值。最差的划分实验结果是b1=81.83, c=265.68, 其余划分实验结果b1>=84.60, c>=313.27
> > > 代码是通过随机种子控制数据集的划分，你可以换几个随机种子试试。 或者你也可以把./data/dataset.py的数据集修改为默认划分验证下性能。
> > 
> > 
> > 前辈，我有一个问题，RSIC是随机划分数据集的，那我只在对比方法时取平均，其他消融实验只固定一个随机数种子来进行实验，这种是允许的吗？毕竟只要能表现出自己模块的作用不就足够了吗？
> 
> 是可以的，但主要还是看reviewer的态度

好的，感谢前辈解惑

**Comment by Lucyhahahahha** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/media/dmd/ours/mlw/pre_model/resnet152.pth' 前辈，这个media文件夹应该去哪里获取呢？

请问您有遇到过”ValueError: DataLoader with IterableDataset: expected unspecified shuffle option, but got shuffle=True“类似的数据加载报错么？报错提示必须将shuffle设置为True，因为pytorch的 IterableDataset包与shuffle=False不兼容？此时使用的torch版本与environment.yml中要求一致呀
